SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

IF (NOT DEFINED ENV{TROUT_TOOLCHAIN_PATH})
    MESSAGE(FATAL_ERROR "Please define environment variable TROUT_TOOLCHAIN_PATH")
ENDIF()

SET(_triple aarch64-none-linux-gnu)
SET(_clang_path $ENV{TROUT_TOOLCHAIN_PATH}/clang-llvm-9)
SET(_gcc_path $ENV{TROUT_TOOLCHAIN_PATH}/gcc-aarch64-none-linux-gnu-9.2-2019.12)

SET(CMAKE_CROSSCOMPILING TRUE)
SET(CMAKE_SYSROOT ${_gcc_path}/aarch64-none-linux-gnu/libc)

SET(CMAKE_C_COMPILER ${_clang_path}/bin/clang)
SET(CMAKE_C_COMPILER_TARGET ${_triple})
SET(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN ${_gcc_path})

SET(CMAKE_CXX_COMPILER ${_clang_path}/bin/clang++)
SET(CMAKE_CXX_COMPILER_TARGET ${_triple})
SET(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN ${_gcc_path})

SET(CMAKE_ASM_COMPILER_TARGET ${_triple})

SET(CMAKE_AR ${_clang_path}/bin/llvm-ar)
SET(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
SET(CMAKE_NM ${_clang_path}/bin/llvm-nm)
SET(CMAKE_RANLIB ${_clang_path}/bin/llvm-ranlib)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
